CREATE TABLE TIPOANIMAL
(
	ID INT PRIMARY KEY IDENTITY,
	DESCRICAO VARCHAR(50)
)
GO
CREATE TABLE ANIMAL
(
	ID INT PRIMARY KEY IDENTITY,
	NOME VARCHAR(100) NOT NULL,
	RACA VARCHAR(100) NULL,
	IDTIPOANIMAL INT NULL,
	PORTE VARCHAR(30) NOT NULL,
	DATANASC SMALLDATETIME NOT NULL,
	FEMEA BIT NOT NULL,

	FOREIGN KEY (IDTIPOANIMAL) REFERENCES TIPOANIMAL (ID)
)
GO
CREATE TABLE CLIENTE
(
	ID INT PRIMARY KEY IDENTITY,
	NOME VARCHAR(100) NOT NULL,
	EMAIL VARCHAR(100) NOT NULL,
	DATANASC SMALLDATETIME NOT NULL,
	TELEFONE VARCHAR(20) NOT NULL,
	DOCIDENTIFICADOR VARCHAR(50) NOT NULL,
)
GO
CREATE TABLE ENDERECO
(
	ID INT PRIMARY KEY IDENTITY,
	LOGRADOURO VARCHAR(100) NOT NULL,
	NUMERO VARCHAR(10) NOT NULL,
	COMPLEMENTO VARCHAR(50) NOT NULL,
	BAIRRO VARCHAR(100) NOT NULL, 
	CIDADE VARCHAR(100) NOT NULL, 
	ESTADO VARCHAR(100) NOT NULL,
	DOCIDENTIFICADOR VARCHAR(50) NOT NULL,
)
GO
CREATE TABLE CLIENTEANIMAL
(
	IDCLIENTE INT NOT NULL,
	IDANIMAL INT NOT NULL, 

	FOREIGN KEY (IDCLIENTE) REFERENCES CLIENTE (ID),
	FOREIGN KEY (IDANIMAL) REFERENCES ANIMAL (ID)

)
GO




